#FIBERDATA is under its own repo, and DATE DESCRIPTION is a separate repo
#THIS WILL REMOVE THE DATE DESCRIPTION GIT LINK SO WHEN RUN GWUSPEC
#RESULT ARE UPLOADED TO FIBERDATA, NOT DATE DESCRIPTION

sudo rm -r .git/
echo 'REMOVED GIT FROM FIBERDATA'
